num1=int(input('Enter number 1: '))
num2=int(input('Enter number 2: '))
print(f"Sum of {num1} and {num2} is: {num1+num2}")
print(f"Difference of {num1} and {num2} is: {num1-num2}")
print(f"Product of {num1} and {num2} is: {num1*num2}")
print(f"Division of {num1} and {num2} is: {num1/num2}")
print(f"Int Division of {num1} and {num2} is: {num1//num2}")
print(f"mod of {num1} and {num2} is: {num1%num2}")
print(f"exponent of {num1} and {num2} is: {num1**num2}")
